/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;

/**
 *
 * @author huyvh
 */
public class DashBoard extends javax.swing.JFrame {

    Color DefauColor, ClickColor;

    public DashBoard() {
        initComponents();
        DefauColor = new Color(0, 204, 204);
        ClickColor = new Color(255, 102, 51);
        // set mau cho pannel
        pnThongKe.setBackground(DefauColor);
        pnBanHang.setBackground(DefauColor);
        pnSanPham.setBackground(DefauColor);
        pnGiamGia.setBackground(DefauColor);
        pnKhachHang.setBackground(DefauColor);
        pnNhanVien.setBackground(DefauColor);
        pnHoaDon.setBackground(DefauColor);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnBackGroudContainer = new javax.swing.JPanel();
        pnMenu = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pnThongKe = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnBanHang = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnSanPham = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnGiamGia = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnKhachHang = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        pnNhanVien = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btnDangXuat = new javax.swing.JButton();
        pnHoaDon = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        content = new javax.swing.JDesktopPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Phần Mền Bán Áo");
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        pnBackGroudContainer.setBackground(new java.awt.Color(0, 0, 0));
        pnBackGroudContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnMenu.setBackground(new java.awt.Color(0, 204, 204));
        pnMenu.setPreferredSize(new java.awt.Dimension(200, 650));
        pnMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 0));
        jLabel3.setText("Thông Tin Đăng Nhập");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pnMenu.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 110));

        pnThongKe.setBackground(new java.awt.Color(255, 102, 51));
        pnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnThongKeMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnThongKeMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/trend_1.png"))); // NOI18N
        jLabel1.setText("THỐNG KÊ");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIconTextGap(10);

        javax.swing.GroupLayout pnThongKeLayout = new javax.swing.GroupLayout(pnThongKe);
        pnThongKe.setLayout(pnThongKeLayout);
        pnThongKeLayout.setHorizontalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThongKeLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addContainerGap(45, Short.MAX_VALUE))
        );
        pnThongKeLayout.setVerticalGroup(
            pnThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThongKeLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pnMenu.add(pnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 220, 50));

        pnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnBanHangMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnBanHangMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/salary.png"))); // NOI18N
        jLabel8.setText("BÁN HÀNG");
        jLabel8.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel8.setIconTextGap(10);

        javax.swing.GroupLayout pnBanHangLayout = new javax.swing.GroupLayout(pnBanHang);
        pnBanHang.setLayout(pnBanHangLayout);
        pnBanHangLayout.setHorizontalGroup(
            pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnBanHangLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel8)
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnBanHangLayout.setVerticalGroup(
            pnBanHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnBanHangLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addContainerGap())
        );

        pnMenu.add(pnBanHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, 50));

        pnSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnSanPhamMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnSanPhamMousePressed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/hawaiian-shirt_1.png"))); // NOI18N
        jLabel9.setText("SẢN PHẨM");
        jLabel9.setIconTextGap(10);

        javax.swing.GroupLayout pnSanPhamLayout = new javax.swing.GroupLayout(pnSanPham);
        pnSanPham.setLayout(pnSanPhamLayout);
        pnSanPhamLayout.setHorizontalGroup(
            pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSanPhamLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel9)
                .addContainerGap(48, Short.MAX_VALUE))
        );
        pnSanPhamLayout.setVerticalGroup(
            pnSanPhamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnSanPhamLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addContainerGap())
        );

        pnMenu.add(pnSanPham, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 220, 50));

        pnGiamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnGiamGiaMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/discounts.png"))); // NOI18N
        jLabel10.setText("GIẢM GIÁ");
        jLabel10.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel10.setIconTextGap(10);

        javax.swing.GroupLayout pnGiamGiaLayout = new javax.swing.GroupLayout(pnGiamGia);
        pnGiamGia.setLayout(pnGiamGiaLayout);
        pnGiamGiaLayout.setHorizontalGroup(
            pnGiamGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnGiamGiaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel10)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        pnGiamGiaLayout.setVerticalGroup(
            pnGiamGiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnGiamGiaLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        pnMenu.add(pnGiamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 220, 50));

        pnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnKhachHangMousePressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/staff.png"))); // NOI18N
        jLabel11.setText("KHÁCH HÀNG");
        jLabel11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel11.setIconTextGap(10);

        javax.swing.GroupLayout pnKhachHangLayout = new javax.swing.GroupLayout(pnKhachHang);
        pnKhachHang.setLayout(pnKhachHangLayout);
        pnKhachHangLayout.setHorizontalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnKhachHangLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addContainerGap(26, Short.MAX_VALUE))
        );
        pnKhachHangLayout.setVerticalGroup(
            pnKhachHangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnKhachHangLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addContainerGap())
        );

        pnMenu.add(pnKhachHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 220, 50));

        pnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnNhanVienMousePressed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/employee_1.png"))); // NOI18N
        jLabel7.setText("NHÂN VIÊN");
        jLabel7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel7.setIconTextGap(10);

        javax.swing.GroupLayout pnNhanVienLayout = new javax.swing.GroupLayout(pnNhanVien);
        pnNhanVien.setLayout(pnNhanVienLayout);
        pnNhanVienLayout.setHorizontalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnNhanVienLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel7)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnNhanVienLayout.setVerticalGroup(
            pnNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnNhanVienLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addContainerGap())
        );

        pnMenu.add(pnNhanVien, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 220, 50));

        btnDangXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/shutdown 24.png"))); // NOI18N
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        pnMenu.add(btnDangXuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 610, -1, -1));

        pnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnHoaDonMousePressed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/bill.png"))); // NOI18N
        jLabel12.setText("HÓA ĐƠN");
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jLabel12.setIconTextGap(10);

        javax.swing.GroupLayout pnHoaDonLayout = new javax.swing.GroupLayout(pnHoaDon);
        pnHoaDon.setLayout(pnHoaDonLayout);
        pnHoaDonLayout.setHorizontalGroup(
            pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnHoaDonLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel12)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        pnHoaDonLayout.setVerticalGroup(
            pnHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnHoaDonLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        pnMenu.add(pnHoaDon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 220, 50));

        pnBackGroudContainer.add(pnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 650));

        javax.swing.GroupLayout contentLayout = new javax.swing.GroupLayout(content);
        content.setLayout(contentLayout);
        contentLayout.setHorizontalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 950, Short.MAX_VALUE)
        );
        contentLayout.setVerticalGroup(
            contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );

        pnBackGroudContainer.add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 950, 650));

        getContentPane().add(pnBackGroudContainer);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDangXuatActionPerformed

    private void pnThongKeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThongKeMousePressed
        // set mau cho pannel
        pnThongKe.setBackground(ClickColor);
        pnBanHang.setBackground(DefauColor);
        pnSanPham.setBackground(DefauColor);
        pnGiamGia.setBackground(DefauColor);
        pnKhachHang.setBackground(DefauColor);
        pnNhanVien.setBackground(DefauColor);
        pnHoaDon.setBackground(DefauColor);
    }//GEN-LAST:event_pnThongKeMousePressed

    private void pnBanHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBanHangMousePressed
        // set mau cho pannel
        pnThongKe.setBackground(DefauColor);
        pnBanHang.setBackground(ClickColor);
        pnSanPham.setBackground(DefauColor);
        pnGiamGia.setBackground(DefauColor);
        pnKhachHang.setBackground(DefauColor);
        pnNhanVien.setBackground(DefauColor);
        pnHoaDon.setBackground(DefauColor);
    }//GEN-LAST:event_pnBanHangMousePressed

    private void pnSanPhamMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnSanPhamMousePressed
        // set mau cho pannel
        pnThongKe.setBackground(DefauColor);
        pnBanHang.setBackground(DefauColor);
        pnSanPham.setBackground(ClickColor);
        pnGiamGia.setBackground(DefauColor);
        pnKhachHang.setBackground(DefauColor);
        pnNhanVien.setBackground(DefauColor);
        pnHoaDon.setBackground(DefauColor);
    }//GEN-LAST:event_pnSanPhamMousePressed

    private void pnGiamGiaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnGiamGiaMousePressed
        // set mau cho pannel
        pnThongKe.setBackground(DefauColor);
        pnBanHang.setBackground(DefauColor);
        pnSanPham.setBackground(DefauColor);
        pnGiamGia.setBackground(ClickColor);
        pnKhachHang.setBackground(DefauColor);
        pnNhanVien.setBackground(DefauColor);
        pnHoaDon.setBackground(DefauColor);
    }//GEN-LAST:event_pnGiamGiaMousePressed

    private void pnKhachHangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnKhachHangMousePressed
        // set mau cho pannel
        pnThongKe.setBackground(DefauColor);
        pnBanHang.setBackground(DefauColor);
        pnSanPham.setBackground(DefauColor);
        pnGiamGia.setBackground(DefauColor);
        pnKhachHang.setBackground(ClickColor);
        pnNhanVien.setBackground(DefauColor);
        pnHoaDon.setBackground(DefauColor);
    }//GEN-LAST:event_pnKhachHangMousePressed

    private void pnNhanVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnNhanVienMousePressed
        // TODO add your handling code here:
        // set mau cho pannel
        pnThongKe.setBackground(DefauColor);
        pnBanHang.setBackground(DefauColor);
        pnSanPham.setBackground(DefauColor);
        pnGiamGia.setBackground(DefauColor);
        pnKhachHang.setBackground(DefauColor);
        pnNhanVien.setBackground(ClickColor);
        pnHoaDon.setBackground(DefauColor);
    }//GEN-LAST:event_pnNhanVienMousePressed

    private void pnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnThongKeMouseClicked
        ViewThongKe view = new ViewThongKe();
        content.removeAll();
        content.add(view).setVisible(true);
    }//GEN-LAST:event_pnThongKeMouseClicked

    private void pnBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnBanHangMouseClicked
        ViewBanHang view = new ViewBanHang();
        content.removeAll();
        content.add(view).setVisible(true);
    }//GEN-LAST:event_pnBanHangMouseClicked

    private void pnSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnSanPhamMouseClicked
        ViewQuanLySanPham view = new ViewQuanLySanPham();
        content.removeAll();
        content.add(view).setVisible(true);
    }//GEN-LAST:event_pnSanPhamMouseClicked

    private void pnHoaDonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnHoaDonMousePressed
        // set mau cho pannel
        pnThongKe.setBackground(DefauColor);
        pnBanHang.setBackground(DefauColor);
        pnSanPham.setBackground(DefauColor);
        pnGiamGia.setBackground(DefauColor);
        pnKhachHang.setBackground(DefauColor);
        pnNhanVien.setBackground(DefauColor);
        pnHoaDon.setBackground(ClickColor);
    }//GEN-LAST:event_pnHoaDonMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JDesktopPane content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel pnBackGroudContainer;
    private javax.swing.JPanel pnBanHang;
    private javax.swing.JPanel pnGiamGia;
    private javax.swing.JPanel pnHoaDon;
    private javax.swing.JPanel pnKhachHang;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnNhanVien;
    private javax.swing.JPanel pnSanPham;
    private javax.swing.JPanel pnThongKe;
    // End of variables declaration//GEN-END:variables
}
